version: '3'
services:
  
  skeduler-app:
    image: sangyun0904/skeduler 
    ports:
      - "8080:8080"
    depends_on:
      - mysql


  mysql:
    image: mysql 
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=skeduler
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "10024:3306"
